events {}

http {

    upstream backend_servers {
        server backend1:3000;
        server backend2:3000;
    }

    
    server {
        listen 4005;
        return 301 https://$host$request_uri;
    }

   
    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/localhost.pem;
        ssl_certificate_key /etc/nginx/certs/localhost-key.pem;

        location / {
            proxy_pass http://backend_servers;
        }
    }
}