// components/tables/authors/data.js

export const authorsData = [
  {
    id: 1,
    name: "Esthera Jackson",
    email: "esthera@simmmple.com",
    avatar: "/avatars/avatar1.png",
    role: "Manager",
    department: "Organization",
    status: "Online",
    employed: "14/06/21",
  },
  {
    id: 2,
    name: "Alexa Liras",
    email: "alexa@simmmple.com",
    avatar: "/avatars/avatar2.png",
    role: "Programmer",
    department: "Developer",
    status: "Offline",
    employed: "14/06/21",
  },
  {
    id: 3,
    name: "Laurent Michael",
    email: "laurent@simmmple.com",
    avatar: "/avatars/avatar3.png",
    role: "Executive",
    department: "Projects",
    status: "Online",
    employed: "14/06/21",
  },
  {
    id: 4,
    name: "Freduardo Hill",
    email: "freduardo@simmmple.com",
    avatar: "/avatars/avatar4.png",
    role: "Manager",
    department: "Organization",
    status: "Online",
    employed: "14/06/21",
  },
  {
    id: 5,
    name: "Daniel Thomas",
    email: "daniel@simmmple.com",
    avatar: "/avatars/avatar5.png",
    role: "Programmer",
    department: "Developer",
    status: "Offline",
    employed: "14/06/21",
  },
  {
    id: 6,
    name: "Mark Wilson",
    email: "mark@simmmple.com",
    avatar: "/avatars/avatar6.png",
    role: "Designer",
    department: "UI/UX Design",
    status: "Offline",
    employed: "14/06/21",
  },
];
