FROM python:3.10-slim

WORKDIR /app


RUN apt-get update && apt-get install -y build-essential gcc g++ && rm -rf /var/lib/apt/lists/*


COPY deploy/ /app/


RUN pip install --no-cache-dir fastapi uvicorn pydantic llama-cpp-python


EXPOSE 8000


CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
