events {}

http {

    server {
        listen 80;
        return 301 https://localhost$request_uri;
    }

    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/localhost.pem;
        ssl_certificate_key /etc/nginx/certs/localhost-key.pem;

        location /api {
            proxy_pass http://backend:5000;
        }

        location /health {
            proxy_pass http://backend:5000;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
}